name: Snap Schedule

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # run every 6 hours at 10 minutes past the hour
    - cron: '10 */6 * * *'

jobs:
  snap:
    name: Invoke Snap
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, core: true }
          - { os: ubuntu-latest }
          - { os: windows-latest }
          - { os: macos-latest }
          - { os: macos-13 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Snap Core
        if: ${{ matrix.core == true }}
        shell: pwsh
        run: ./snap.ps1

      - name: Snap Toolchain
        if: ${{ matrix.core != true }}
        shell: pwsh
        run: ./snap.ps1 -SnapToolchain

      - name: Upload Index
        uses: actions/upload-artifact@v4
        with:
          path: ./tmp/index-*.json

  merge:
    needs: snap
    name: Update Index
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Index
        uses: actions/download-artifact@v4
        with:
          path: ./tmp

      - name: Merge Index
        shell: pwsh
        run: ./snap.ps1 -Merge

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: deployed
          keep_files: true
